language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
install:
  - python setup.py install
  - pip install nose --use-mirrors
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
script: nosetests
env:
  global:
    - TEST_MSTRANSLATOR_CLIENT_ID=python-mstranslator
    - TEST_MSTRANSLATOR_CLIENT_SECRET=FkVf1TWUiEpT6FXGgEkFhzGmDzye6xJ6E0WXpvE64HA=
